name: Repository Dispatch
on:
  repository_dispatch:
    types: [release-leafygreen-ui]
jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: post-release/update-packages
      - name: Use Node 16
        uses: actions/setup-node@v3
        if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        with:
          node-version: '16'
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: yarn install
      - run: yarn update-packages '${{ github.event.client_payload.packages }}'
      - name: pull-request
        run: gh pr create -B staging -H post-release/update-packages --title 'Automated PR - Update packages' --body 'Automated PR to update LGUI packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
