name: on-pr
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  verify-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Build NextJS
      run: next build
    - name: Build Vercel
      run: vercel build
