name: on-pr
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

env:
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
  types:
    runs-on: ubuntu-latest
    name: Types
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install
      - name: TypeCheck
        run: yarn check:ts
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install
      - name: Build NextJS
        run: yarn build
