on:
  push:
    branches:
    - staging

jobs:
  create-pr-to-main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        pr_title: "Automated PR: staging to main"
        github_token: ${{ secrets.GITHUB_TOKEN }}