on:
  push:
    branches:
    - staging

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        pr_title: "Automated PR: ${{ github.ref }} into main"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}